# iantom.com
# Author: John DiMona

application: iantom-com
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
  
handlers:

- url: /(\w+)(/\w*\.js)
  static_files: \1\2
  upload: (\w+)/(.*\.js)
  mime_type: text/javascript

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  script: main.py

- url: /.*
  script: main.py