# iantom.com
# Author: John DiMona

application: iantom-com
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
  
handlers:

- url: /
  script: main.py

- url: /.*
  script: main.py